{{- $fullName := include "tc-server.fullname" $ -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-agent-role
  labels:
    {{- include "tc-server.labels" . | nindent 4 }}
rules:
- apiGroups: [""] 
  resources: ["pods", "pods/log"]
  verbs: ["*"]
- apiGroups: ["*"] 
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: ["*"] 
  resources: ["namespace"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}-agent-role-binding
  labels:
    {{- include "tc-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-agent-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.agent_runner_name  | default (printf "%s-eks-agent-runner" .Release.Name ) }}
