{{- $fullName := include "tc-server.fullname" $ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-front
  labels:
    {{- include "tc-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: front
    {{- include "tc-server.selectorLabels" . | nindent 4 }}