{{- if .Values.ingress.enabled -}}
{{- $fullName := include "tc-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $gitVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">1.19-0" $gitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $gitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "tc-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if semverCompare ">1.19-0" $gitVersion }}
          - path: "/"
            pathType: "Prefix"

            backend:
              service:
                name: {{ $fullName }}-front
                port:
                  number: 80
          {{- else }}
          - path: "/"
            backend:
              serviceName: {{ $fullName }}-front
              servicePort: 80
          {{- end }}
{{- end }}